### ISSUE TITLE
offenseに「offenseを無視することが正当であるケース」を入れるフィールドを追加する

### ISSUE THREAD

**Issue by pocke** [rubocop-hq/rubocop-jp#21]
たとえば、 [querly](https://github.com/soutaro/querly)には、警告にjustification という項目が存在します。querly公式のサンプルにjustificationsがのってなくてつらいのですが、こんな感じです。

```yaml
rules:
  - id: com.sideci.find_with_bang
    pattern: "find_by(_) [!conditional]"
    message: find_byは対象のレコードが見つからない場合にnilを返します。find_by!を利用しましょう。
    justification: nilが返ってくることを期待する場合
```

このようにjustificationがあることで、Lintがfalse positiveを出した場合にユーザーがそれをfalse positiveだと判断できるようになります。
現状ユーザーが「本当にこの警告に従うべきなのか」と思った時に、RuboCopは参考になるような情報をなにも提供していないので、これによって「従わなくても良い」ケースに関してはそう言えるようにしたいと思っています。

  https://teratail.com/questions/99932 は、「justificationがあれば質問をせずすぐ解決できた」実際の事例です。こういうことは結構たくさん起きていると思うので、この機能を追加することで迷ってしまう体験を減らしたいなーと思っています
