### ISSUE TITLE
0.53 から出力される overrides the same parameter を抑止したい

### ISSUE THREAD

**Issue by krororo** [rubocop-hq/rubocop-jp#39]
0.53.0 から同じパラメータを上書きしていると `overrides the same parameter` と出力されるようになりました。

Exclude, Include については `inherit_mode` を設定することによって、メッセージが出なくなったのですが、
Metrics の Max パラメータについては `inherit_mode` を設定してもメッセージが出力されてしまいます。

設定で回避する手段はあるのでしょうか？

rubocop.yml の設定はこのような感じになっています。

```yaml
inherit_gem:
  rubocop-shared-config: rubocop.yml # 複数プロジェクトで共通。ここに Metrics の推奨 Max 値を設定

inherit_from: .rubocop_todo.yml # ここにプロジェクト固有の Metrics Max 値を設定
inherit_mode:
  override:
    - Max
```
rubocop を実行すると以下のような出力がされます。
```
$ bundle exec rubocop
.rubocop.yml: Metrics/AbcSize:Max overrides the same parameter in .rubocop_todo.yml
```
rubocop のバージョン
```
$ bundle exec rubocop -V 
0.53.0 (using Parser 2.5.0.2, running on ruby 2.4.3 x86_64-linux)
```
