### ISSUE TITLE
Layouts/DefEndAlignment Cop で怒られる場合と怒られない場合がある

### ISSUE THREAD

**Issue by skmtpalm** [rubocop-hq/rubocop-jp#44]
`Layouts/DefEndAlignment`  Cop の挙動について質問させてください！
gem `ruboco-airbnb` を継承して使っているのですが、こちらの設定には特におかしいところがなさそうだったので、こちらで質問させていただきました。

https://github.com/airbnb/ruby/tree/master/rubocop-airbnb

＜怒られたり怒られなかったりするコード例＞
```ruby
# Warning Layouts/DefEndAlignment end at 6, 2 is not aligned with ApplicationController
# app/controller/some/categories_contriller.rb
class Some::CategoriesController < ApplicationController
  def show
    #..some code...
  end
end

# Not Warning Some Controller
# app/controller/some/products_controller.rb
class Some::ProductsController < ApplicationController
  SOME_CONSTANT = 10
  def show
    # ...some code...
  end
end
```

.rubocop.yml
```yml
inherit_from:
  - .rubocop_airbnb.yml
  - .rubocop_todo.yml

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.4.1
  Exclude:
    - vendor/bundle/**/*
    - bin/*
    - db/**/*
    - config/**/*
    - Gemfile
```

rubocop-airbnb のDefEndAlignement の設定箇所
```yml
...
Layout/DefEndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: start_of_line
  AutoCorrect: false
...
```

Cop 対象のコントローラー（some/categories_controller.rb) で  `class` の直下にコードを何か挿入すると怒られなくなります。
（例えば、対象のコントローラーのように定数を入れたり、`before_action` など入れても怒られない）

他の挙動として
```ruby
# ApplicationController がトップの定数だと明示すると怒られない
class Some::CategoriesController < ::ApplicationController
  #...
end
```

ここの挙動と対処の仕方がどうしても理解できず issue を立てさせていただきました。よろしくお願いします！

Gemfile.lock
```
rails (~> 5.1.3)

rubocop(0.57.2)
rubocop-airbnb (1.5.0)
    rubocop (= 0.57.2)
    rubocop-rspec (= 1.27.0)
rubocop-rspec (1.27.0)
    rubocop (>= 0.56.0)
```

ruby-version : 2.4.1p111
