### ISSUE TITLE
RSpec::ContextWording で 接尾辞でも設定できるようにしたい

### ISSUE THREAD

**Issue by kyohah** [rubocop-hq/rubocop-jp#49]
https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/ContextWording
```
# Overview
`context` block descriptions should start with 'when', or 'with'.

Prefixes:
  - when
  - with
  - without
  - if
```

現状Prefixesしか設定できず、
日本語でrspecを書く場合
```
context '画面に表示されていないとき'
context '画面に表示されていない場合'
```
のように`とき`や`場合`などの`Suffixes`の設定ができるようにしたいと思いました。

実装してPRを出そうとしたのですが、
`RSpec::ContextWording`の条件の部分は
```
desctiprion # 'with metadata hash'
prefixes # ['when', 'with']
def bad_prefix?(description)
  !prefixes.include?(description.split.first)
end
```
https://github.com/rubocop-hq/rubocop-rspec/blob/0442757fb4af570994b37b3e0ca35baeec635eb0/lib/rubocop/cop/rspec/context_wording.rb#L45

`desctiprion`が`画面に表示されていない場合`のような日本語は`split`できません。

- `Patterns:`のようなオプションで正規表現で実装するのがよいのでしょうか
- 日本語で`context`を書くのを辞めるのがよいのでしょうか
よろしくおねがいします

**Comment by pocke** [comment]
Suffixes を指定できるようにするのは良いと思います。その場合「Prefixesにマッチしない」かつ「Suffixesにマッチしない」時に警告を出すのが合理的なように思います。

> `desctiprion`が`画面に表示されていない場合`のような日本語は`split`できません。

これはちょっと厄介ですね。。実装するとしたら、

* `Patterns`オプションに正規表現を指定する
* 別途`Split: true|false`のようなオプションを用意して、Splitをするか単に前方一致/後方一致だけを見るかを切り替える

のどちらかになるかなと思います。

機能自体はreasonableなので受け入れられると思います。日本語の説明をするのがちょっと厄介ですが…。

英語を書くのが手間でなかったら、rubocop-rspecの方にIssueを立ててもらうことはできますか？ 実装方法に選択肢があるので、他の人の意見もきいてみたいです。

**Comment by pocke** [comment]
FYIですが、querlyというツールを使うと同様のチェックをすることができます。
https://github.com/soutaro/querly

次のYAMLを`querly.yml`として保存して、`querly check`コマンドを実行するとチェックできます。

```yaml
rules:
  - id: ja.rspec.context_warding
    pattern:
      - subject: "context(!:string: as 'sentence, ...)"
        where:
          sentence:
            - /場合$/
            - /とき$/
      - subject: "describe(!:string: as 'sentence, ...)"
        where:
          sentence:
            - /場合$/
            - /とき$/
    message: 'RSpecのcontext、describeの説明文は「場合」もしくは「とき」で終わる必要があります'
    examples:
      - before: 'context "画面に表示されていない" do; end'
        after: 'context "画面に表示されていないとき" do; end'
      - before: 'describe "画面に表示されていない" do; end'
        after: 'describe "画面に表示されていない場合" do; end'
check:
  - path: /spec
    rules:
      - ja.rspec.context_warding
```


追記: あ、このパターンだと`describe SomeClassName`にも警告が出てしまう気がしますね。ちゃんと使うにはその辺を調整したほうが良さそう
